"use client"

import { useState, useEffect } from "react"

const mockSpeciesData = {
  "misty-lake": [
    {
      id: "water-lily",
      commonName: "Water Lily",
      scientificName: "Nymphaea alba",
      habitat: "Freshwater lakes and ponds",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=400&h=300&fit=crop",
      description: "Beautiful aquatic flowering plant with large floating leaves.",
      conservationStatus: "Least Concern",
    },
    {
      id: "great-blue-heron",
      commonName: "Great Blue Heron",
      scientificName: "Ardea herodias",
      habitat: "Wetlands, lakes, and rivers",
      type: "Bird",
      diet: "Fish, frogs, and small mammals",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Large wading bird known for its patient hunting style.",
      conservationStatus: "Least Concern",
    },
    {
      id: "mallard-duck",
      commonName: "Mallard Duck",
      scientificName: "Anas platyrhynchos",
      habitat: "Lakes, ponds, and wetlands",
      type: "Bird",
      diet: "Aquatic plants, insects, small fish",
      image: "https://images.unsplash.com/photo-1551522435-a13afa10f103?w=400&h=300&fit=crop",
      description: "Common waterfowl found in freshwater habitats worldwide.",
      conservationStatus: "Least Concern",
    },
    {
      id: "cattail",
      commonName: "Cattail",
      scientificName: "Typha latifolia",
      habitat: "Wetlands and marsh edges",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1566146991569-696da38bb775?w=400&h=300&fit=crop",
      description: "Tall wetland plant with distinctive brown cylindrical flower spikes.",
      conservationStatus: "Least Concern",
    },
    {
      id: "painted-turtle",
      commonName: "Painted Turtle",
      scientificName: "Chrysemys picta",
      habitat: "Ponds, lakes, and slow streams",
      type: "Reptile",
      diet: "Aquatic plants, insects, small fish",
      image: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=400&h=300&fit=crop",
      description: "Colorful freshwater turtle often seen basking on logs.",
      conservationStatus: "Least Concern",
    },
    {
      id: "dragonfly",
      commonName: "Blue Dragonfly",
      scientificName: "Libellula luctuosa",
      habitat: "Near water bodies",
      type: "Insect",
      diet: "Flying insects",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
      description: "Agile aerial predator that hunts other flying insects.",
      conservationStatus: "Least Concern",
    },
    {
      id: "bass-fish",
      commonName: "Largemouth Bass",
      scientificName: "Micropterus salmoides",
      habitat: "Freshwater lakes and ponds",
      type: "Fish",
      diet: "Smaller fish, insects, frogs",
      image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop",
      description: "Popular game fish known for its fighting ability.",
      conservationStatus: "Least Concern",
    },
    {
      id: "beaver",
      commonName: "North American Beaver",
      scientificName: "Castor canadensis",
      habitat: "Lakes, ponds, and streams",
      type: "Mammal",
      diet: "Tree bark, aquatic plants",
      image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&h=300&fit=crop",
      description: "Large rodent that builds dams and lodges.",
      conservationStatus: "Least Concern",
    },
  ],
  "ancient-grove": [
    {
      id: "giant-redwood",
      commonName: "Giant Redwood",
      scientificName: "Sequoia sempervirens",
      habitat: "Coastal fog belt",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop",
      description: "Among the tallest trees on Earth, can live over 2,000 years.",
      conservationStatus: "Vulnerable",
    },
    {
      id: "spotted-owl",
      commonName: "Spotted Owl",
      scientificName: "Strix occidentalis",
      habitat: "Old-growth forests",
      type: "Bird",
      diet: "Small mammals and birds",
      image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop",
      description: "Nocturnal hunter that depends on old-growth forest habitat.",
      conservationStatus: "Near Threatened",
    },
    {
      id: "douglas-fir",
      commonName: "Douglas Fir",
      scientificName: "Pseudotsuga menziesii",
      habitat: "Temperate rainforests",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      description: "Large coniferous tree important for timber and wildlife habitat.",
      conservationStatus: "Least Concern",
    },
    {
      id: "black-bear",
      commonName: "American Black Bear",
      scientificName: "Ursus americanus",
      habitat: "Dense forests",
      type: "Mammal",
      diet: "Omnivorous - berries, fish, small mammals",
      image: "https://images.unsplash.com/photo-1446329813274-7c9036bd9a1f?w=400&h=300&fit=crop",
      description: "Large omnivorous mammal that plays a key role in forest ecosystems.",
      conservationStatus: "Least Concern",
    },
    {
      id: "banana-slug",
      commonName: "Pacific Banana Slug",
      scientificName: "Ariolimax columbianus",
      habitat: "Moist forest floors",
      type: "Mollusk",
      diet: "Decomposing plant matter",
      image: "https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=400&h=300&fit=crop",
      description: "Large yellow slug that helps decompose forest floor material.",
      conservationStatus: "Least Concern",
    },
    {
      id: "sword-fern",
      commonName: "Western Sword Fern",
      scientificName: "Polystichum munitum",
      habitat: "Forest understory",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=400&h=300&fit=crop",
      description: "Large evergreen fern common in Pacific Northwest forests.",
      conservationStatus: "Least Concern",
    },
    {
      id: "marbled-murrelet",
      commonName: "Marbled Murrelet",
      scientificName: "Brachyramphus marmoratus",
      habitat: "Old-growth coastal forests",
      type: "Bird",
      diet: "Small fish and marine invertebrates",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Seabird that nests in old-growth forest canopies.",
      conservationStatus: "Endangered",
    },
  ],
  meadow: [
    {
      id: "monarch-butterfly",
      commonName: "Monarch Butterfly",
      scientificName: "Danaus plexippus",
      habitat: "Open fields and meadows",
      type: "Insect",
      diet: "Nectar from flowers",
      image: "https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=400&h=300&fit=crop",
      description: "Famous for its incredible migration journey across North America.",
      conservationStatus: "Endangered",
    },
    {
      id: "black-eyed-susan",
      commonName: "Black-eyed Susan",
      scientificName: "Rudbeckia hirta",
      habitat: "Prairies and meadows",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1597848212624-e593c83edd72?w=400&h=300&fit=crop",
      description: "Bright yellow wildflower that blooms throughout summer.",
      conservationStatus: "Least Concern",
    },
    {
      id: "meadowlark",
      commonName: "Western Meadowlark",
      scientificName: "Sturnella neglecta",
      habitat: "Grasslands and meadows",
      type: "Bird",
      diet: "Insects and seeds",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Songbird known for its beautiful melodic calls.",
      conservationStatus: "Near Threatened",
    },
    {
      id: "purple-coneflower",
      commonName: "Purple Coneflower",
      scientificName: "Echinacea purpurea",
      habitat: "Prairie and meadow edges",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1566146991569-696da38bb775?w=400&h=300&fit=crop",
      description: "Native wildflower with medicinal properties.",
      conservationStatus: "Least Concern",
    },
    {
      id: "bumblebee",
      commonName: "Common Bumblebee",
      scientificName: "Bombus impatiens",
      habitat: "Flower-rich meadows",
      type: "Insect",
      diet: "Nectar and pollen",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
      description: "Important pollinator for many wildflower species.",
      conservationStatus: "Vulnerable",
    },
    {
      id: "field-mouse",
      commonName: "Meadow Vole",
      scientificName: "Microtus pennsylvanicus",
      habitat: "Grasslands and meadows",
      type: "Mammal",
      diet: "Grasses and seeds",
      image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&h=300&fit=crop",
      description: "Small rodent that creates runways through tall grass.",
      conservationStatus: "Least Concern",
    },
    {
      id: "goldenrod",
      commonName: "Canada Goldenrod",
      scientificName: "Solidago canadensis",
      habitat: "Open fields and roadsides",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1597848212624-e593c83edd72?w=400&h=300&fit=crop",
      description: "Late-blooming wildflower important for fall pollinators.",
      conservationStatus: "Least Concern",
    },
    {
      id: "red-winged-blackbird",
      commonName: "Red-winged Blackbird",
      scientificName: "Agelaius phoeniceus",
      habitat: "Wetlands and meadows",
      type: "Bird",
      diet: "Seeds, insects, small fruits",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Distinctive bird with bright red shoulder patches.",
      conservationStatus: "Least Concern",
    },
    {
      id: "grasshopper",
      commonName: "Field Grasshopper",
      scientificName: "Chorthippus brunneus",
      habitat: "Dry grasslands and meadows",
      type: "Insect",
      diet: "Grasses and herbs",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
      description: "Common jumping insect that feeds on grass.",
      conservationStatus: "Least Concern",
    },
  ],
  woodland: [
    {
      id: "red-fox",
      commonName: "Red Fox",
      scientificName: "Vulpes vulpes",
      habitat: "Forests and woodlands",
      type: "Mammal",
      diet: "Omnivorous - small mammals, birds, insects, fruits",
      image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=400&h=300&fit=crop",
      description: "Adaptable predator known for its intelligence and cunning.",
      conservationStatus: "Least Concern",
    },
    {
      id: "white-oak",
      commonName: "White Oak",
      scientificName: "Quercus alba",
      habitat: "Mixed deciduous forests",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      description: "Majestic tree that can live for several centuries.",
      conservationStatus: "Least Concern",
    },
    {
      id: "cardinal",
      commonName: "Northern Cardinal",
      scientificName: "Cardinalis cardinalis",
      habitat: "Woodland edges and gardens",
      type: "Bird",
      diet: "Seeds, fruits, and insects",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Bright red songbird, state bird of seven US states.",
      conservationStatus: "Least Concern",
    },
    {
      id: "maple-tree",
      commonName: "Sugar Maple",
      scientificName: "Acer saccharum",
      habitat: "Deciduous forests",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      description: "Deciduous tree famous for its fall colors and maple syrup.",
      conservationStatus: "Near Threatened",
    },
    {
      id: "gray-squirrel",
      commonName: "Eastern Gray Squirrel",
      scientificName: "Sciurus carolinensis",
      habitat: "Deciduous and mixed forests",
      type: "Mammal",
      diet: "Nuts, seeds, and fruits",
      image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&h=300&fit=crop",
      description: "Common tree squirrel important for seed dispersal.",
      conservationStatus: "Least Concern",
    },
    {
      id: "wild-turkey",
      commonName: "Wild Turkey",
      scientificName: "Meleagris gallopavo",
      habitat: "Mixed forests and clearings",
      type: "Bird",
      diet: "Seeds, nuts, insects, small reptiles",
      image: "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=400&h=300&fit=crop",
      description: "Large ground bird native to North America.",
      conservationStatus: "Least Concern",
    },
    {
      id: "trillium",
      commonName: "White Trillium",
      scientificName: "Trillium grandiflorum",
      habitat: "Rich woodland floors",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1566146991569-696da38bb775?w=400&h=300&fit=crop",
      description: "Spring wildflower with distinctive three-petaled white blooms.",
      conservationStatus: "Vulnerable",
    },
    {
      id: "woodpecker",
      commonName: "Pileated Woodpecker",
      scientificName: "Dryocopus pileatus",
      habitat: "Mature forests",
      type: "Bird",
      diet: "Insects, especially carpenter ants",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Large woodpecker with distinctive red crest.",
      conservationStatus: "Least Concern",
    },
  ],
  "mountain-ridge": [
    {
      id: "mountain-goat",
      commonName: "Mountain Goat",
      scientificName: "Oreamnos americanus",
      habitat: "Rocky alpine areas",
      type: "Mammal",
      diet: "Grasses, herbs, and shrubs",
      image: "https://images.unsplash.com/photo-1446329813274-7c9036bd9a1f?w=400&h=300&fit=crop",
      description: "Sure-footed climber adapted to steep rocky terrain.",
      conservationStatus: "Least Concern",
    },
    {
      id: "alpine-forget-me-not",
      commonName: "Alpine Forget-me-not",
      scientificName: "Myosotis alpestris",
      habitat: "High mountain meadows",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1566146991569-696da38bb775?w=400&h=300&fit=crop",
      description: "Small blue flowers that bloom in harsh alpine conditions.",
      conservationStatus: "Near Threatened",
    },
    {
      id: "golden-eagle",
      commonName: "Golden Eagle",
      scientificName: "Aquila chrysaetos",
      habitat: "Mountain ranges and open country",
      type: "Bird",
      diet: "Small to medium mammals",
      image: "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=400&h=300&fit=crop",
      description: "Powerful raptor with excellent eyesight and hunting skills.",
      conservationStatus: "Least Concern",
    },
    {
      id: "pika",
      commonName: "American Pika",
      scientificName: "Ochotona princeps",
      habitat: "Rocky alpine slopes",
      type: "Mammal",
      diet: "Alpine plants and grasses",
      image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&h=300&fit=crop",
      description: "Small mammal that collects plants for winter storage.",
      conservationStatus: "Vulnerable",
    },
    {
      id: "alpine-buttercup",
      commonName: "Alpine Buttercup",
      scientificName: "Ranunculus glacialis",
      habitat: "High altitude rocky areas",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1597848212624-e593c83edd72?w=400&h=300&fit=crop",
      description: "Hardy wildflower that blooms at extreme altitudes.",
      conservationStatus: "Least Concern",
    },
    {
      id: "marmot",
      commonName: "Yellow-bellied Marmot",
      scientificName: "Marmota flaviventris",
      habitat: "Rocky mountain slopes",
      type: "Mammal",
      diet: "Grasses, flowers, and seeds",
      image: "https://images.unsplash.com/photo-1446329813274-7c9036bd9a1f?w=400&h=300&fit=crop",
      description: "Large ground squirrel that hibernates through winter.",
      conservationStatus: "Least Concern",
    },
  ],
  "pine-forest": [
    {
      id: "white-pine",
      commonName: "Eastern White Pine",
      scientificName: "Pinus strobus",
      habitat: "Coniferous forests",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop",
      description: "Tall coniferous tree with soft, blue-green needles.",
      conservationStatus: "Least Concern",
    },
    {
      id: "pine-marten",
      commonName: "American Pine Marten",
      scientificName: "Martes americana",
      habitat: "Coniferous forests",
      type: "Mammal",
      diet: "Small mammals, birds, insects",
      image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=400&h=300&fit=crop",
      description: "Agile predator that hunts in trees and on the ground.",
      conservationStatus: "Near Threatened",
    },
    {
      id: "crossbill",
      commonName: "Red Crossbill",
      scientificName: "Loxia curvirostra",
      habitat: "Coniferous forests",
      type: "Bird",
      diet: "Conifer seeds",
      image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop",
      description: "Specialized finch with crossed bill tips for extracting seeds.",
      conservationStatus: "Least Concern",
    },
  ],
  "river-valley": [
    {
      id: "river-otter",
      commonName: "North American River Otter",
      scientificName: "Lontra canadensis",
      habitat: "Rivers and streams",
      type: "Mammal",
      diet: "Fish, amphibians, crustaceans",
      image: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=400&h=300&fit=crop",
      description: "Playful aquatic mammal excellent at swimming and diving.",
      conservationStatus: "Least Concern",
    },
    {
      id: "willow-tree",
      commonName: "Weeping Willow",
      scientificName: "Salix babylonica",
      habitat: "Near water sources",
      type: "Plant",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      description: "Graceful tree with drooping branches often found near water.",
      conservationStatus: "Least Concern",
    },
    {
      id: "kingfisher",
      commonName: "Belted Kingfisher",
      scientificName: "Megaceryle alcyon",
      habitat: "Rivers, streams, and lakes",
      type: "Bird",
      diet: "Fish and aquatic invertebrates",
      image: "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=400&h=300&fit=crop",
      description: "Diving bird that catches fish with precise aerial attacks.",
      conservationStatus: "Near Threatened",
    },
  ],
}

export function useSpeciesData(regionId: string) {
  const [species, setSpecies] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchSpeciesData = async () => {
      setLoading(true)
      setError(null)

      try {
        await new Promise((resolve) => setTimeout(resolve, 1000))

        const mockData = mockSpeciesData[regionId as keyof typeof mockSpeciesData] || []
        setSpecies(mockData)
      } catch (err) {
        setError("Failed to fetch species data")
        const mockData = mockSpeciesData[regionId as keyof typeof mockSpeciesData] || []
        setSpecies(mockData)
      } finally {
        setLoading(false)
      }
    }

    if (regionId) {
      fetchSpeciesData()
    }
  }, [regionId])

  return { species, loading, error }
}
